Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -22,29 +22,42 @@ trigger_internal_ci:
     - export TRIGGER_BRANCH=${CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME}
     - export CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
     - |
-      curl -fksSL --header \
-      "PRIVATE-TOKEN:${SVC_HLS_RENDER_API}" \
-      "${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/repository/branches/${CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME}" \
-        || export TRIGGER_BRANCH='master'
-    - echo "Going to trigger pipeline on ${TRIGGER_BRANCH} branch in downstream project (id ${DOWNSTREAM_PROJECT_ID})"
-    # Trigger downstream project and wait for it. 
-    - |
-      resp=$(curl -fksSL --request POST --form "token=${CI_JOB_TOKEN}" --form "variables[CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME]=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME" --form "ref=${TRIGGER_BRANCH}" ${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/trigger/pipeline)
-      id=$(echo $resp | jq -r '.id')
-      web_url=$(echo $resp | jq -r '.web_url')
-      echo "Waiting for pipeline $web_url ..."
-      # Wait 30 mins (10 seconds x 180 times)
-      for retry in $(seq 1 180); do
-        status=$(curl -s --header "PRIVATE-TOKEN:${SVC_HLS_RENDER_API}" "${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/pipelines/$id" | jq -r '.status')
-        echo "Got pipeline status $status, retry $retry/180"
-        [[ $status == "success" || $status == "failed" ]] && break
-        sleep 10
-      done
+      #curl -fksSL --header \
+      #"PRIVATE-TOKEN:${SVC_HLS_RENDER_API}" \
+      #"${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/repository/branches/${CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME}" \
+      #  || export TRIGGER_BRANCH="$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
+      
+      #Creating a new branch
+      curl --request POST --header \ 
+      "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" \
+      "${CI_SERVER_URL}/api/v4/projects/$DOWNSTREAM_PROJECT_ID/repository/branches?branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&ref=master"
+      
+      #Creating a new MR 
+      curl --request POST --header \ 
+      "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" \
+      "${CI_SERVER_URL}/api/v4/projects/$DOWNSTREAM_PROJECT_ID/merge_requests?source_branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&target_branch=master&title=PullReqFrom_$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
+      
+      
+      
+#     - echo "Going to trigger pipeline on ${TRIGGER_BRANCH} branch in downstream project (id ${DOWNSTREAM_PROJECT_ID})"
+#     # Trigger downstream project and wait for it. 
+#     - |
+#       resp=$(curl -fksSL --request POST --form "token=${CI_JOB_TOKEN}" --form "variables[CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME]=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME" --form "ref=${TRIGGER_BRANCH}" ${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/trigger/pipeline)
+#       id=$(echo $resp | jq -r '.id')
+#       web_url=$(echo $resp | jq -r '.web_url')
+#       echo "Waiting for pipeline $web_url ..."
+#       # Wait 30 mins (10 seconds x 180 times)
+#       for retry in $(seq 1 180); do
+#         status=$(curl -s --header "PRIVATE-TOKEN:${SVC_HLS_RENDER_API}" "${CI_SERVER_URL}/api/v4/projects/${DOWNSTREAM_PROJECT_ID}/pipelines/$id" | jq -r '.status')
+#         echo "Got pipeline status $status, retry $retry/180"
+#         [[ $status == "success" || $status == "failed" ]] && break
+#         sleep 10
+#       done
 
-      if [[ $status != "success" ]]; then
-        echo "$web_url has status $status, failing"
-        exit 1
-      fi
+#       if [[ $status != "success" ]]; then
+#         echo "$web_url has status $status, failing"
+#         exit 1
+#       fi
 
 # # So far environment variables can't be passed to the bridge job. Once it became available we could use following:
 # trigger_internal_ci:
